export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const DELETE_COURSES_SUCCESS = "DELETE_COURSES_SUCCESS";
export const LOAD_COURSE = "LOAD_COURSE";
export const LOAD_COURSE_SUCCESS = "LOAD_COURSE_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
