export const BEGIN_AJAX_REQUEST = "BEGIN_AJAX_REQUEST";
export const FINISHED_AJAX_REQUEST_SUCCESS = "FINISHED_AJAX_REQUEST_SUCCESS";

export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const DELETE_COURSES_SUCCESS = "DELETE_COURSES_SUCCESS";
export const LOAD_COURSE = "LOAD_COURSE";
export const LOAD_COURSE_SUCCESS = "LOAD_COURSE_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
